services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORTFOLIO_EMAIL=${PORTFOLIO_EMAIL}
      - PORTFOLIO_URL=${PORTFOLIO_URL}
