import { DM_Sans } from 'next/font/google';

import Footer from './components/Footer';
import Navbar from './components/Navbar';

import type { Metadata } from 'next';

import './globals.css';

const dmSans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0' />
        <link rel='icon' href='sygnet.svg' type='image/svg+xml' />

        <title>Portfolio</title>
      </head>
      <body className={dmSans.className}>
        <div className='mx-auto max-w-screen-xl px-4'>
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
