import { DM_Sans } from 'next/font/google';

import Navbar from './components/Navbar';

import type { Metadata } from 'next';

import './globals.css';

const dmSans = DM_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={dmSans.className}>
        <div className='mx-auto max-w-screen-xl px-4'>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
